#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt update
sudo apt install -y nginx
cd /var/www/ || exit
sudo chmod 777 html
echo 'Hello World!' > html/index.html
sudo chmod 755 html
cd /etc/nginx/ || exit
sudo chmod 777 sites-available
sudo chmod 777 sites-available/default
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
                try_files \$uri \$uri/ =404;
    }

    location /redirect_me{
        return 301 https://www.alxafrica.com;
    }
}" > sites-available/default
sudo chmod 644 sites-available/default
sudo chmod 755 sites-available
cd ~ || exit
sudo service nginx restart

