#!/usr/bin/env bash
# Configure Nginx server to have a 404 error page.

sudo apt update
sudo apt install -y nginx
cd /var/www/ || exit
sudo chmod 777 html
echo 'Hello World!' > html/index.html
echo "Ceci n'est pas une page" > html/err_page.html
sudo chmod 755 html
cd /etc/nginx/ || exit
sudo chmod 777 sites-available
sudo chmod 777 sites-available/default
echo "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     error_page 404 /err_page.html;

     root /var/www/html;

     index index.html index.htm index.nginx-debian.html;
     server_name _;

     location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying an err_page.html.
                try_files \$uri \$uri/ =/var/www/html/err_page.html;
    }

    location /redirect_me{
        return 301 https://www.alxafrica.com =/var/www/html/err_page.html;
    }

    location = /err_page.html {
        root /var/www/html;
        internal;
}" > sites-available/default
sudo chmod 644 sites-available/default
sudo chmod 755 sites-available
cd ~ || exit
sudo service nginx restart
