#!/usr/bin/env bash
# Configure Nginx server so that its HTTP response contains a custom header

sudo apt update
sudo apt install -y nginx
cd /var/www/ || exit
sudo chmod 777 html
echo 'Hello World!' > html/index.html
echo "Ceci n'est pas une page" > html/error_page.html
sudo chmod 755 html
cd /etc/nginx/ || exit
sudo chmod 777 sites-available
sudo chmod 777 sites-available/default
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    error_page 404 /error_page.html;

    server_name _;

    location / {
		# First attempt to serve request as file, then
                # as directory, then fall back to displaying an error_page.html.
                add_header X-Served-By \"\$hostname\"
                try_files \$uri \$uri /error_page;
    }

    location = /error_page.html {
        root /var/www/html;
        internal;
    }
    location /redirect_me{
        return 301 https://www.alxafrica.com;
    }
}" > sites-available/default
sudo chmod 644 sites-available/default
sudo chmod 755 sites-available
cd ~ || exit
sudo service nginx restart

